src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Cocur\Slugify\Slugify;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity("title")
 * @Vich\Uploadable()
 */
class Property
{
    public const HEAT = [
        0 => 'electric',
        1 => 'gaz'
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="5", max="200")
     */
    private ?string $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private ?int $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $price;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private ?string $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private bool $sold = false;

    /**
     * @var Datetime|null
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @var ArrayCollection
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     */
    private $imageFile;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $filename;

    /**
     * @var Datetime|null
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function __construct()
    {
        $this->created_at = new DateTime();
        $this->updated_at = new DateTime();
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return string
     */
    public function getFormatedPrice(): string
    {
        $price = ($this->price) ? (float)$this->price : 0.0;
        return number_format($price, 0, '', ' ');
    }

    /**
     * @return string
     */
    public function getSlug(): string
    {
        $title = ($this->title) ? $this->title : '';
        return (new Slugify())->slugify($title);
    }

    /**
     * @return string
     */
    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->removeElement($option)) {
            $option->removeProperty($this);
        }

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return Property
     */
    public function setImageFile(?File $imageFile): self
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new DateTime('now');
        }
        return $this;
    }

    /**
     * @return string|null
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param string|null $filename
     * @return Property
     */
    public function setFilename(?string $filename): self
    {
        $this->filename = $filename;
        return $this;
    }

    public function getUpdatedAt(): ?DateTime
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(DateTime $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    /**
     * @template T of FormBuilderInterface
     * @param T $builder
     * @param mixed[] $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => array_flip(Property::HEAT)
            ])
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'choice_label' => 'name',
                'multiple' => true
            ])
            ->add('imageFile', FileType::class, [
                'required' => false
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('sold');
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class PropertyController
 * @package App\Controller
 */
class PropertyController extends AbstractController
{

    /**
     * @var PropertyRepository
     */
    private PropertyRepository $repository;
    /**
     * @var ObjectManager
     */
    private ObjectManager $em;

    public function __construct(PropertyRepository $repository, EntityManagerInterface $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }

    /**
     * @Route("/biens", name="property.index")
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        $properties = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page', 1),
            12
        );

        return $this->render('property/index.html.twig', [
            'current_menu' => 'properties',
            'properties' => $properties,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/biens/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*", "id": "\d+"})
     * @param Property $property
     * @param string $slug
     * @return Response
     */
    public function show(Property $property, string $slug): Response
    {
        if ($property->getSlug() !== $slug) {
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ], 301);
        }

        return $this->render('property/show.html.twig', [
            'property' => $property
        ]);
    }
}

templates/property/_property.html.twig
<div class="card mb-4">
  {% if property.filename %}
{#    <img src="/images/properties/{{ property.filename }}" alt="card-img-top" style="width: 100%; height: auto;">#}
    <img src="{{ vich_uploader_asset(property) }}" alt="card-img-top"  class="img-fluid" style="width: 100%; height: auto;">
  {% endif %}
  <div class="card-body">
    <h5 class="card-title">
      <a href="{{ path('property.show', {slug: property.slug, id: property.id}) }}">
        {{ property.title }}
      </a>
    </h5>
{#    <div class="card-text">{{ property.description | nl2br }}</div>#}
    <p class="card-text">{{ property.surface }} m² - {{ property.city }} ({{ property.postalCode }})</p>
    <div class="text-primary" style="font-size: 2rem; font-weight:bold;">
      {{ property.formatedPrice }} XOF
    </div>
  </div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tous les biens{% endblock %}

{% block body %}
  <div class="jumbotron mt-4">
    <div class="container">
      {{ form_start(form) }}
      <div class="form-row row align-items-end">
        <div class="col-md-3">
          {{ form_row(form.minSurface) }}
        </div>
        <div class="col-md-3">
          {{ form_row(form.maxPrice) }}
        </div>
        <div class="col-md-3">
          {{ form_row(form.options) }}
        </div>
        <div class="col-md-3">
          <button style="margin-top: auto" class="btn btn-primary">Rechercher</button>
        </div>
      </div>
      {{ form_end(form) }}
    </div>
  </div>
  <div class="container mt-4">
    <h1>Voir tous vos biens</h1>
    <div class="row">
      {% for property in properties %}
        <div class="col-md-4">
          {{ include('property/_property.html.twig') }}
        </div>
      {% endfor %}
    </div>

    <div class="pagination">
      {{ knp_pagination_render(properties) }}
    </div>
  </div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
  <div class="jumbotron">

    <div class="container">
      <div class="row">
        <div class="col-md-8">
        </div>
        <div class="col-md-4">
          <h1>{{ property.title }}</h1>
          <h2>{{ property.rooms }} pièces - {{ property.surface }} m²</h2>
          <div class="text-primary" style="font-size: 4rem; font-weight:bold;">{{ property.formatedPrice }} XOF</div>
          <a href="#" class="btn btn-primary">Contacter l'agence</a>
        </div>
      </div>
    </div>
  </div>
  <div class="container mt-4">
    <p>
      {{ property.description | nl2br }}
    </p>

    <div class="row">
      <div class="col-md-8">
        <h2>Caractéristiques</h2>
        <table class="table table-striped">
          <tr>
            <td>Surface habitable</td>
            <td>{{ property.surface }} m²</td>
          </tr>
          <tr>
            <td>Pièces</td>
            <td>{{ property.rooms }}</td>
          </tr>
          <tr>
            <td>Chambres</td>
            <td>{{ property.bedrooms }}</td>
          </tr>
          <tr>
            <td>Etage</td>
            <td>{{ property.floor }}</td>
          </tr>
          <tr>
            <td>Chauffage</td>
            <td>{{ property.heatType }}</td>
          </tr>
        </table>
      </div>
      <div class="col-md-4">
        <h2>Spécificités</h2>
      </div>
    </div>
  </div>
{% endblock %}

{% block title %}

{% endblock %}
